### ISSUE TITLE
簡訊出現 %0A

### ISSUE THREAD

**Issue by haer0248** [GoneTone/1922-sms-real-link#1]
普通簡訊不會有問題，但是只要是掃描頁面 QR Code的並發送簡訊，就會出現 (例如4人) **%2B4%0A**。

**Comment by GoneTone** [comment]
目前已作修復 https://github.com/GoneTone/1922-sms-real-link/commit/137028556bd0052c434ef31b5449fc0219e00a82

不過部分簡訊應用程式會遺失同行人數前的 + 號，會遺失 + 的都是要 encodeURIComponent() 兩次，但包兩次就會出現您的那狀況，所以我們新增了訊息提醒。
